<?php echo $this->render('/partial/top.phtml'); ?>

    <?php echo $this->render('/partial/header.phtml'); ?>

    <?php echo $this->render('/partial/sidemenu.phtml'); ?>

    <!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">

		<?php echo $this->content; ?>

	</div>
	<!-- /.content-wrapper -->
	<footer class="main-footer">
		<div class="pull-right hidden-xs">
			<b>Version</b> <?php echo $this->config('app_version'); ?>
		</div>
		<strong>Copyright &copy; 2014-2016 <a href="<?php echo $this->config('app_copyright_url'); ?>"><?php echo $this->config('app_copyright'); ?></a>.</strong> All rights reserved.
	</footer>

	<aside class="control-sidebar control-sidebar-dark"></aside>
	<!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
	<div class="control-sidebar-bg"></div>

<?php echo $this->render('/partial/bottom.phtml'); ?>