    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Twitools <i class="fa fa-fw fa-twitter" style="color: lightblue;"></i></h1>
                        <p class="intro-text">A free, intuitive, all-in-one tools for Twitter.
                            <br>by <span style="color: lightblue;">Kupretz</span></p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>About Twitools <i class="fa fa-fw fa-twitter" style="color: lightblue;"></i></h2>
                <p>
                    Twitools <i class="fa fa-fw fa-twitter" style="color: lightblue;"></i> is a collection of tools that will help you manage, improve, and get more of your Twitter account.
                </p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Twitools</h2>
                    <p>You can download Twitools for free on the preview page at Start Bootstrap.</p>
                    <a href="http://startbootstrap.com/template-overviews/Twitools/" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Us</h2>
                <p>Feel free to email us to provide some feedback on Twitools, give us suggestions for new functions, improvements, or to just say hello!</p>
                <p><a href="mailto:twitools@kupretz.com">twitools@kupretz.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/tw1tools" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/agsapt/twitools" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+twitools/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; <b>Twi</b>tools 2017</p>
        </div>
    </footer>